mixed-port: 10801
allow-lan: true
mode: rule
log-level: debug
external-controller: :9090
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
global-client-fingerprint: chrome
# interface-name: WLAN
ipv6: false

tun:
  enable: true
  device: meta              #MacOS建议删除此项
  stack: system             #system / gvisor / lwip liwp仅为1.13.2以上的功能
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  # mtu: 9000               #最大传输单元
  # strict_route: true      #将所有连接路由到tun来防止泄漏，但你的设备将无法其他设备被访问
  # inet4_route_address:      #启用 auto_route 时使用自定义路由而不是默认路由
  #   - 0.0.0.0/1
  #   - 128.0.0.0/1
  # inet6_route_address:      #启用 auto_route 时使用自定义路由而不是默认路由
  #   - '::/1'
  #   - '8000::/1'

listeners:
  - name: socks5-in-1
    type: socks
    port: 2023
    rule: sub-browser
proxy-groups:
  # url-test 将按照 url 测试结果使用延迟最低节点
  - name: "auto"
    type: url-test
    proxies:
      - bart
      - nerd
      - bart_hysteria
      - nerd_hysteria
    # tolerance: 150
    # lazy: true
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300
# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
dns:
  enable: true # 是否启用dns false
  ipv6: false
  # prefer-h3: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  # use-hosts: true 
  fake-ip-range: 198.18.0.1/16
  default-nameserver: 
    - 223.5.5.5 # 阿里DNS
    - 8.8.8.8
    # - tls://223.5.5.5:853
  nameserver-policy:
   'spcnwikia.top': '223.5.5.5'
   'domain:xjtu.edu.cn': '223.5.5.5'
  #  '+.internal.crop.com': '10.0.0.1'
  #  'geosite:cn': https://doh.pub/dns-query
  #  'geosite:geolocation-!cn': [tls://8.8.4.4, https://1.0.0.1/dns-query]
  #  "www.baidu.com,+.google.cn": [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
  #  "geosite:private,apple": [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
  nameserver:
    - 223.5.5.5
    - https://dns.alidns.com/dns-query
    - 119.29.29.29
    # - tls://223.5.5.5:853 # 百度DNS
  fallback:
   - 8.8.8.8
   - https://1.1.1.1/dns-query
   - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    # ipcidr:
    #   - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  # 配置不使用 fake-ip 的域名
  fake-ip-filter:
    - "+.lan"
    # QQ Loopback
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - "+.linksys.com"
    - "+.pool.ntp.org"
    # Router
    - hiwifi.com
    - leike.cc
    - miwifi.com
    - my.router
    - peiluyou.com
    - phicomm.me
    - router.ctc
    - routerlogin.com
      # Tenda router
    - tendawifi.com
      # TP-Link router
    - tplinkwifi.net
      # Windows
    - “+.msftconnecttest.com”
    - “+.msftncsi.com”
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
      # 中興路由器
    - zte.home
      # Stun Services
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
      # Google Voices
    - "lens.l.google.com"
      # Nintendo Switch
    - "+.srv.nintendo.net"
      # PlayStation
    - "+.stun.playstation.net"
      # XBox
    - "xbox.*.*.microsoft.com"
    - "+.xboxlive.com"
      # Bilibili CDN
    - "+.mcdn.bilivideo.cn"
    - "*bili*"
proxies:
  # - name: "bart"
  #   type: trojan
  #   server: bart.howies.live
  #   port: 1462
  #   password: "a4e080df-c2aa-4c05-b759-6cd11bb59fc1"
  #   tls: true
  #   sni: bart.howies.live
  #   alpn: 
  #    - http/1.1
  - name: "bart"
    type: vless
    server: 156.251.130.60
    port: 1562
    uuid: "a4e080df-c2aa-4c05-b759-6cd11bb59fc1"
    network: tcp
    tls: true
    # udp: true
    flow: xtls-rprx-vision
    servername: addons.mozilla.org
    reality-opts:
      public-key: kYeE-oaxiQgCfi7S8Jhino3qqrmcajwiQRPC30ZxCHQ
    client-fingerprint: firefox # cannot be empty
  # - name: "nerd"
  #   type: trojan
  #   server: homer.howies.live
  #   port: 443
  #   password: "7c72e318-0386-46f8-bfef-faa1956cf101"
  #   sni: homer.howies.live
  #   tls: true
  #   alpn: 
  #    - http/1.1
  - name: "nerd"
    type: vless
    server: 198.211.6.60
    port: 1562
    uuid: "7c72e318-0386-46f8-bfef-faa1956cf101"
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: addons.mozilla.org
    reality-opts:
      public-key: 2kGoqYzgdEChZ5I6b2NRtSlLMSaDCZhbxaJ1IrF2whg
    client-fingerprint: firefox # cannot be empty
  - name: "bart_hysteria"
    type: hysteria
    server: bart.howies.live
    port: 10000
    auth_str:  "a4e080df-c2aa-4c05-b759-6cd11bb59fc1" # 将会在未来某个时候删除
    # auth-str: yourpassword
    # obfs: obfs_str
    alpn:
      - h3
    protocol: udp # 支持 udp/wechat-video/faketcp
    up: "50 Mbps" # 若不写单位，默认为 Mbps
    down: "100 Mbps" # 若不写单位，默认为 Mbps
    sni: bart.howies.live
    # skip-cert-verify: false
    # recv_window_conn: 12582912 # 将会在未来某个时候删除
    # recv-window-conn: 12582912
    # recv_window: 52428800 # 将会在未来某个时候删除
    # recv-window: 52428800
    # ca: "./my.ca"
    # ca_str: "xyz" # 将会在未来某个时候删除
    # ca-str: "xyz"
    # disable_mtu_discovery: false
    # fingerprint: xxxx
    # fast-open: true # 支持 TCP 快速打开，默认为 false
  - name: "nerd_hysteria"
    type: hysteria
    server: homer.howies.live
    port: 10000
    auth_str:  "7c72e318-0386-46f8-bfef-faa1956cf101" # 将会在未来某个时候删除
    # auth-str: yourpassword
    # obfs: obfs_str
    alpn:
      - h3
    protocol: udp # 支持 udp/wechat-video/faketcp
    up: "50 Mbps" # 若不写单位，默认为 Mbps
    down: "100 Mbps" # 若不写单位，默认为 Mbps
    sni: homer.howies.live
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  ############################# 自定义 #############################
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,google,auto
  - DOMAIN-KEYWORD,carbon,auto
  - DOMAIN,usegalaxy.org,DIRECT
  - DOMAIN-KEYWORD,bing,auto
  - DOMAIN-SUFFIX,linuxcontainers.org,auto
  - DOMAIN-SUFFIX,sourceforge.net,auto
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  # - DOMAIN,sg.imedicaldoctor.net,REJECT
  - DOMAIN,spcnwikia.top,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  ##################################################################
  - RULE-SET,applications,DIRECT
  - RULE-SET,private,DIRECT
  # - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,auto
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,auto
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,auto
sub-rules:
  sub-browser:
  - DOMAIN-KEYWORD,openai,bart
  - DOMAIN,usegalaxy.org,auto
  - MATCH,auto