mixed-port: 10801
allow-lan: true
mode: rule
log-level: debug
external-controller: :9090
geox-url:
  geoip: "https://gh-proxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://gh-proxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
global-client-fingerprint: chrome
# interface-name: WLAN
ipv6: false

tun:
  enable: true
  device: meta              #MacOS建议删除此项
  stack: mixed             #system / gvisor / lwip liwp仅为1.13.2以上的功能
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  # mtu: 9000               #最大传输单元
  # strict_route: true      #将所有连接路由到tun来防止泄漏，但你的设备将无法其他设备被访问
  # inet4_route_address:      #启用 auto_route 时使用自定义路由而不是默认路由
  #   - 0.0.0.0/1
  #   - 128.0.0.0/1
  # inet6_route_address:      #启用 auto_route 时使用自定义路由而不是默认路由
  #   - '::/1'
  #   - '8000::/1'

proxy-groups:
  # url-test 将按照 url 测试结果使用延迟最低节点
  - name: "auto_xray_only"
    type: url-test
    proxies:
      - bart
      - vmiss
    url: "https://cp.cloudflare.com/generate_204"
    interval: 60
    tolerance: 50
  - name: "auto_all"
    type: url-test
    proxies:
      - bart
      - vmiss
      - vmiss_hysteria
      - bart_hysteria
      - bart_tuic
    url: "https://cp.cloudflare.com/generate_204"
    interval: 60
    tolerance: 50
  - name: "bart_all"
    type: url-test
    proxies:
      - bart
      - bart_hysteria
      - bart_tuic
    url: "https://cp.cloudflare.com/generate_204"
    interval: 60
    tolerance: 50
# profile:
#   store-selected: true
#   store-fake-ip: true
# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
dns:
  enable: true # 是否启用dns false
  ipv6: false
  prefer-h3: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  # use-hosts: true 
  fake-ip-range: 198.18.0.1/16
  default-nameserver: 
    - 223.5.5.5 # 阿里DNS
    - 8.8.8.8
    - 1.1.1.1
  nameserver-policy:
   'spcnwikia.top': 'https://dns.alidns.com/dns-query'
   'domain:xjtu.edu.cn': 'https://dns.alidns.com/dns-query'
   'geosite:openai': 'https://1.1.1.1/dns-query'
   'geosite:microsoft': 'https://1.1.1.1/dns-query'
   'geosite:msn': 'https://1.1.1.1/dns-query'
   'geosite:bing': 'https://1.1.1.1/dns-query'
   'bingapis.com': 'https://1.1.1.1/dns-query'
   '+.bing.com': 'https://1.1.1.1/dns-query'
   'geosite:gfw': [https://1.1.1.1/dns-query, https://dns.google/dns-query]
  #  '+.internal.crop.com': '10.0.0.1'
  #  'geosite:cn': https://doh.pub/dns-query
  #  'geosite:geolocation-!cn': [tls://8.8.4.4, https://1.0.0.1/dns-query]
  #  "www.baidu.com,+.google.cn": [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
  #  "geosite:private,apple": [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
  nameserver:
   - tls://223.5.5.5
   - https://223.5.5.5/dns-query#h3=true
   - https://doh.pub/dns-query
  fallback:
   - https://1.1.1.1/dns-query
   - https://dns.cloudflare.com/dns-query#h3=true
   - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  # 配置不使用 fake-ip 的域名
  fake-ip-filter:
    - "*.lan"
    # QQ Loopback
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - "+.linksys.com"
    - "+.pool.ntp.org"
    # Router
    - hiwifi.com
    - leike.cc
    - miwifi.com
    - my.router
    - peiluyou.com
    - phicomm.me
    - router.ctc
    - routerlogin.com
      # Tenda router
    - tendawifi.com
      # TP-Link router
    - tplinkwifi.net
      # Windows
    - “+.msftconnecttest.com”
    - “+.msftncsi.com”
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
      # 中興路由器
    - zte.home
      # Stun Services
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
      # Google Voices
    - "lens.l.google.com"
      # Nintendo Switch
    - "+.srv.nintendo.net"
      # PlayStation
    - "+.stun.playstation.net"
      # XBox
    - "xbox.*.*.microsoft.com"
    - "+.xboxlive.com"
      # Bilibili CDN
    - "+.mcdn.bilivideo.cn"
    - "*bili*"
proxies:
  - name: "bart"
    type: vless
    server: 156.251.130.60
    port: 18718
    uuid: 2958f6f6-9f70-48ce-b6fe-bf7ae11725e6
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: "lol.secure.dyn.riotcdn.net"
    reality-opts:
      public-key: oj3i0N2TzANtrAZ-ClcDpXjvn6UegoWDnc8QzuihwVo
    client-fingerprint: chrome
  - name: "vmiss"
    type: vless
    server: 45.93.28.208
    port: 443
    uuid: 4f17dca2-f67d-4a9c-8bec-fab0160f5f09
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: vmiss.howies.live
    reality-opts:
      public-key: CPQoSrhCSPCH7VH26ozE7stujTwyFv-hH9vyjJeEECE
     # short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome # cannot be empty
  - name: "vmiss_hysteria"
    type: hysteria2
    server: vmiss.howies.live
    port: 23221
    password: 4f17dca2-f67d-4a9c-8bec-fab0160f5f09
    # obfs: salamander # 默认为空，如果填写则开启obfs，目前仅支持salamander
    # obfs-password: yourpassword
    sni: vmiss.howies.live
    # skip-cert-verify: false
    # fingerprint: xxxx
    alpn:
      - h3
    # ca: "./my.ca"
    # ca-str: "xyz"
  - name: "bart_hysteria"
    type: hysteria2
    server: 156.251.130.60
    port: 40843
    password: 2958f6f6-9f70-48ce-b6fe-bf7ae11725e6
    # obfs: salamander # 默认为空，如果填写则开启obfs，目前仅支持salamander
    # obfs-password: yourpassword
    sni: bart.howies.live
    # skip-cert-verify: false
    # fingerprint: xxxx
    alpn:
      - h3
    # ca: "./my.ca"
    # ca-str: "xyz"
  - name: "bart_tuic"
    server: bart.howies.live
    port: 27629
    type: tuic
    uuid: "2958f6f6-9f70-48ce-b6fe-bf7ae11725e6"
    password: "2958f6f6-9f70-48ce-b6fe-bf7ae11725e6"
    ip: 156.251.130.60
    # heartbeat-interval: 10000
    alpn: [h3]
    disable-sni: true
    reduce-rtt: true
    request-timeout: 8000
    udp-relay-mode: native
    congestion-controller: bbr
    # max-udp-relay-packet-size: 1500
    # fast-open: true
    # skip-cert-verify: true
    # max-open-streams: 20
    # sni: example.com


rules:
  ############################# 自定义 #############################
  - GEOSITE,category-ads-all,REJECT
  ############################# Adobe activation ##################
  - GEOSITE,adobe-activation,REJECT
  - DOMAIN-SUFFIX,ic.adobe.io,REJECT
  - DOMAIN-SUFFIX,7sj9n87sls.adobe.io,REJECT
  - DOMAIN-SUFFIX,ij0gdyrfka.adobe.io,REJECT
  - DOMAIN-SUFFIX,lm.licenses.adobe.com,REJECT
  - DOMAIN-SUFFIX,na2m-pr.licenses.adobe.com,REJECT
  - DOMAIN-SUFFIX,practivate.adobe.com,REJECT
  - DOMAIN-SUFFIX,activate.adobe.com,REJECT
  - DOMAIN-SUFFIX,ereg.adobe.com,REJECT
  - DOMAIN-SUFFIX,wip.adobe.com,REJECT
  - DOMAIN-SUFFIX,lmlicenses.wip4.adobe.com,REJECT
  - DOMAIN-SUFFIX,na1r.services.adobe.com,REJECT
  - DOMAIN-SUFFIX,hlrcv.stage.adobe.com,REJECT
  - DOMAIN-SUFFIX,genuine.adobe.com,REJECT
  - DOMAIN-SUFFIX,prod.adobegenuine.com,REJECT
  - DOMAIN-SUFFIX,cc-api-data.adobe.io,REJECT
  # - DOMAIN-SUFFIX,ims-prod06.adobelogin.com,REJECT
  - DOMAIN-SUFFIX,p13n.adobe.io,REJECT
  - DOMAIN-SUFFIX,crs.cr.adobe.com,REJECT
  - DOMAIN-SUFFIX,lcs-cops.adobe.io,REJECT
  # - DOMAIN-SUFFIX,hbrt.adobe.com,REJECT
  - DOMAIN-SUFFIX,23ynjitwt5.adobe.io,REJECT
  - DOMAIN-SUFFIX,butler.adobe.com,REJECT
  - DOMAIN-SUFFIX,acp-ss-va6c2.adobe.io,REJECT
  - AND,((PROCESS-NAME,Illustrator.exe),(DOMAIN-SUFFIX,adobe.io)),REJECT
 ############################# End Adobe activation ##################
  - SUB-RULE,(SRC-PORT,10801),sub-browser
  - GEOSITE,openai,bart_all
  - DOMAIN-SUFFIX,bard.google.com,bart_all
  - DOMAIN-SUFFIX,oaiusercontent.com,bart_all
  - GEOSITE,paypal,bart_all
  - GEOSITE,google,auto_xray_only
  - GEOSITE,github,auto_xray_only
  - PROCESS-NAME,Obsidian.exe,auto_xray_only
  - DOMAIN-KEYWORD,carbon,auto_xray_only
  - DOMAIN-SUFFIX,usegalaxy.org,DIRECT
  - DOMAIN-SUFFIX,misakaf.org,auto_all
  - DOMAIN-KEYWORD,bing,bart_all
  - GEOSITE,bing,bart_all
  - GEOSITE,spotify,bart_all
  - GEOSITE,spotify,bart_all
  - DOMAIN-SUFFIX,linuxcontainers.org,auto_xray_only
  - DOMAIN-SUFFIX,sourceforge.net,auto_xray_only
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-KEYWORD,spcnwiki,DIRECT
  # - DOMAIN,sg.imedicaldoctor.net,REJECT
  - DOMAIN-SUFFIX,spcnwikia.top,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,steam,bart_all
  - GEOSITE,geolocation-!cn,auto_xray_only
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT
  - IP-CIDR,223.5.5.5/32,DIRECT
  - IP-CIDR,119.29.29.29/32,DIRECT
  - IP-CIDR,180.76.76.76/32,DIRECT
  ##################################################################
  - IP-CIDR,1.1.1.1/32,auto_all
  - IP-CIDR,1.0.0.1/32,auto_all
  - IP-CIDR,8.8.8.8/32,auto_all
  - IP-CIDR,8.8.4.4/32,auto_all
  - GEOIP,us,auto_xray_only
  - GEOIP,ca,auto_xray_only
  - GEOIP,telegram,auto_xray_only
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,auto_all
sub-rules:
  sub-browser:
    - GEOSITE,paypal,bart_all
    - GEOSITE,openai,bart_all
    - GEOSITE,github,auto_xray_only
    - GEOSITE,steam,bart_all
    - GEOSITE,category-entertainment,auto_all
